# Site settings
title: Aunitz Giménez Mendiburu - Consultor y director de proyectos digitales
subtitle: Aunitz Giménez
header-img: img/home-bg.jpg
email: aunitz@gmail.com
copyright_name: Aunitz Giménez Mendiburu
description: "Dirección de proyectos digitales y consultoría tecnológica. Especialista en usabilidad, accesibilidad y desarrollo de soluciones en entorno web."
baseurl: ""
url: "https://www.aunitz.net"
twitter_username:
github_username: aunitz
facebook_username:
email_username:
linkedin_username: aunitz
#medium_username: aunitz

# Origen de la plantilla
# https://startbootstrap.com/template-overviews/clean-blog/

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-90648162-1

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus: aunitz

# Build settings
markdown: kramdown
#highlighter: rouge
#permalink: pretty
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md",resources]

gems: [jekyll-paginate, jekyll-feed]
